#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
#  Generate clawd_mochi_companion/wifi_secrets.h from environment vars.
#
#  WiFi credentials never enter git. This script reads WIFI_SSID_N /
#  WIFI_PASS_N pairs (N = 1, 2, 3, ...) from the environment and writes
#  a gitignored wifi_secrets.h that the firmware #includes.
#
#  Usage:
#    WIFI_SSID_1='your-ssid'   WIFI_PASS_1='your-password' \
#    WIFI_SSID_2='your-ssid-2' WIFI_PASS_2='your-password-2' \
#    ./scripts/gen_wifi_secrets.sh
#
#  To persist the vars, add them to ~/.zshrc (or a gitignored .envrc)
#  and re-run this script whenever your networks change.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../clawd_mochi_companion/wifi_secrets.h"

c_escape() {
  # Escape backslash and double-quote for a C string literal.
  local s=${1//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

entries=()
i=1
while :; do
  ssid_var="WIFI_SSID_$i"
  pass_var="WIFI_PASS_$i"
  ssid="${!ssid_var:-}"
  pass="${!pass_var:-}"
  [ -z "$ssid" ] && break
  entries+=( "  { \"$(c_escape "$ssid")\", \"$(c_escape "$pass")\" }," )
  i=$((i + 1))
done

if [ ${#entries[@]} -eq 0 ]; then
  echo "No WIFI_SSID_N/WIFI_PASS_N env vars set. Aborting." >&2
  echo "Example:" >&2
  echo "  WIFI_SSID_1='your-ssid'   WIFI_PASS_1='your-password' \\" >&2
  echo "  WIFI_SSID_2='your-ssid-2' WIFI_PASS_2='your-password-2' \\" >&2
  echo "  $0" >&2
  exit 1
fi

{
  echo "// AUTO-GENERATED by scripts/gen_wifi_secrets.sh — do not edit by hand."
  echo "// Regenerate after changing WiFi env vars. Gitignored: never committed."
  echo "#pragma once"
  echo ""
  echo "struct WifiCred { const char* ssid; const char* pass; };"
  echo ""
  echo "const WifiCred WIFI_GROUP[] = {"
  printf '%s\n' "${entries[@]}"
  echo "};"
  echo ""
  echo "const int WIFI_GROUP_COUNT = sizeof(WIFI_GROUP) / sizeof(WIFI_GROUP[0]);"
} > "$OUT"

echo "Wrote $OUT with $((i - 1)) network(s)."
